#34 Enhance Docker Security and Best Practices
OneBusAway/docker pull request #40
Opened 2024-02-22 06:55 UTC by myselfdeepdas

This pull request introduces improvements to enhance the security and follow best practices when running Docker containers for the OBA server and the transit data bundler.

### Changes Made:

1. **oba/Dockerfile:**
    - Create a non-root user ('oba') for improved security.
    - Switch to the non-root user for subsequent Dockerfile steps.
    - Refactor the Dockerfile to align with Docker best practices.

2. **bundler/Dockerfile:**
    - Create a non-root user ('oba') for enhanced security.
    - Switch to the non-root user for the remaining Dockerfile steps.
    - Adjust the Dockerfile according to best practices.

### Context:

The changes aim to minimize the potential security risks associated with running containers as the root user. Following best practices, we've created a dedicated non-root user for the containers, reducing the attack surface and enhancing the overall security posture.

Please review and merge these changes to ensure a more secure and reliable deployment of the OBA server and the transit data bundler containers.

Thank you!

2024-02-22 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-docker?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-docker?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-docker?pullRequest=40) it.</sub>

2024-02-23 16:10 UTC, aaronbrethorst requested changes
These Dockerfiles will no longer work after the changes that are in this PR. It almost looks like the output of ChatGPT with the comments saying "Continue with the rest of the Dockerfile as the non-root user" in the Dockerfiles

2024-02-23 16:59 UTC, myselfdeepdas commented
Check it out—I made some changes

2024-02-25 16:39 UTC, Neo2308 commented on oba/Dockerfile
> -RUN wget "https://repo.camsys-apps.com/releases/org/onebusaway/onebusaway-api-webapp/${OBA_VERSION}/onebusaway-api-webapp-${OBA_VERSION}.war"
Removing these wget statements seems to be unintentional. Could you revert?

2024-02-29 04:09 UTC, aaronbrethorst commented
Superseded by #55

2024-02-29 04:09 UTC, closed without merging